2025-10-16 11:34:03,980 INFO    MainThread:1853794 [wandb_setup.py:_flush():81] Current SDK version is 0.22.2
2025-10-16 11:34:03,980 INFO    MainThread:1853794 [wandb_setup.py:_flush():81] Configure stats pid to 1853794
2025-10-16 11:34:03,980 INFO    MainThread:1853794 [wandb_setup.py:_flush():81] Loading settings from /ssd/chenxi/.config/wandb/settings
2025-10-16 11:34:03,981 INFO    MainThread:1853794 [wandb_setup.py:_flush():81] Loading settings from /ssd/chenxi/research/CriticSearch/wandb/settings
2025-10-16 11:34:03,981 INFO    MainThread:1853794 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-10-16 11:34:03,981 INFO    MainThread:1853794 [wandb_init.py:setup_run_log_directory():705] Logging user logs to /ssd/chenxi/research/CriticSearch/wandb/run-20251016_113403-tmlzg8na/logs/debug.log
2025-10-16 11:34:03,981 INFO    MainThread:1853794 [wandb_init.py:setup_run_log_directory():706] Logging internal logs to /ssd/chenxi/research/CriticSearch/wandb/run-20251016_113403-tmlzg8na/logs/debug-internal.log
2025-10-16 11:34:03,981 INFO    MainThread:1853794 [wandb_init.py:init():832] calling init triggers
2025-10-16 11:34:03,981 INFO    MainThread:1853794 [wandb_init.py:init():837] wandb.init called with sweep_config: {}
config: {'data': {'tokenizer': None, 'train_files': 'data/CriticSearch_dataset/train.parquet', 'val_files': 'data/CriticSearch_dataset/test.parquet', 'train_data_num': None, 'val_data_num': None, 'prompt_key': 'prompt', 'max_prompt_length': 4096, 'max_response_length': 500, 'max_start_length': 2048, 'max_obs_length': 2048, 'train_batch_size': 64, 'val_batch_size': 64, 'return_raw_input_ids': False, 'return_raw_chat': False, 'shuffle_train_dataloader': True}, 'actor_rollout_ref': {'hybrid_engine': True, 'model': {'path': 'models/Qwen/Qwen2.5-0.5B-Instruct', 'external_lib': None, 'override_config': {}, 'enable_gradient_checkpointing': True, 'use_remove_padding': True}, 'actor': {'strategy': 'fsdp', 'ppo_mini_batch_size': 256, 'ppo_micro_batch_size': 64, 'use_dynamic_bsz': False, 'ppo_max_token_len_per_gpu': 16384, 'grad_clip': 1.0, 'state_masking': True, 'clip_ratio': 0.2, 'entropy_coeff': 0.001, 'use_kl_loss': True, 'kl_loss_coef': 0.001, 'kl_loss_type': 'low_var_kl', 'ppo_epochs': 1, 'shuffle': False, 'ulysses_sequence_parallel_size': 1, 'optim': {'lr': 1e-06, 'lr_warmup_steps_ratio': 0.95, 'min_lr_ratio': None, 'warmup_style': 'constant', 'total_training_steps': 203}, 'fsdp_config': {'wrap_policy': {'min_num_params': 0}, 'param_offload': True, 'grad_offload': True, 'optimizer_offload': True, 'fsdp_size': -1}}, 'ref': {'fsdp_config': {'param_offload': True, 'wrap_policy': {'min_num_params': 0}, 'fsdp_size': -1}, 'log_prob_micro_batch_size': 128, 'log_prob_use_dynamic_bsz': False, 'log_prob_max_token_len_per_gpu': 16384, 'ulysses_sequence_parallel_size': 1}, 'rollout': {'name': 'vllm', 'temperature': 1, 'top_k': -1, 'top_p': 0.95, 'prompt_length': 4096, 'response_length': 500, 'dtype': 'bfloat16', 'gpu_memory_utilization': 0.6, 'ignore_eos': False, 'enforce_eager': True, 'free_cache_engine': True, 'load_format': 'dummy_dtensor', 'tensor_model_parallel_size': 1, 'max_num_batched_tokens': 8192, 'max_num_seqs': 1024, 'log_prob_micro_batch_size': 128, 'log_prob_use_dynamic_bsz': False, 'log_prob_max_token_len_per_gpu': 16384, 'do_sample': True, 'n': 1, 'n_agent': 5}}, 'critic': {'strategy': 'fsdp', 'optim': {'lr': 1e-05, 'lr_warmup_steps_ratio': 0.0, 'min_lr_ratio': None, 'warmup_style': 'constant', 'total_training_steps': 203}, 'model': {'path': '~/models/deepseek-llm-7b-chat', 'tokenizer_path': 'models/Qwen/Qwen2.5-0.5B-Instruct', 'override_config': {}, 'external_lib': None, 'enable_gradient_checkpointing': False, 'use_remove_padding': False, 'fsdp_config': {'param_offload': False, 'grad_offload': False, 'optimizer_offload': False, 'wrap_policy': {'min_num_params': 0}, 'fsdp_size': -1}}, 'ppo_mini_batch_size': 256, 'ppo_micro_batch_size': 64, 'forward_micro_batch_size': 64, 'use_dynamic_bsz': False, 'ppo_max_token_len_per_gpu': 32768, 'forward_max_token_len_per_gpu': 32768, 'ulysses_sequence_parallel_size': 1, 'ppo_epochs': 1, 'shuffle': False, 'grad_clip': 1.0, 'cliprange_value': 0.5}, 'reward_model': {'enable': False, 'strategy': 'fsdp', 'model': {'input_tokenizer': 'models/Qwen/Qwen2.5-0.5B-Instruct', 'path': '~/models/FsfairX-LLaMA3-RM-v0.1', 'external_lib': None, 'use_remove_padding': False, 'fsdp_config': {'min_num_params': 0, 'param_offload': False}}, 'micro_batch_size': 64, 'max_length': None, 'ulysses_sequence_parallel_size': 1, 'use_dynamic_bsz': False, 'forward_max_token_len_per_gpu': 32768}, 'retriever': {'llm_ip': 'localhost', 'retriever_ip': 'localhost', 'topk': 5, 'search_mode': 'wiki', 'simulate_llm': 'models/iic/Simulation_LLM_google_3B', 'start_threshold': 0, 'end_threshold': 0.5, 'temperature': 0.8, 'search_engine': 'wiki'}, 'user': {'llm_ip': 'localhost', 'user_ip': 'localhost', 'topk': 5, 'user_mode': 'simulate_prompt', 'simulate_llm': 'None', 'start_threshold': 0.5, 'end_threshold': 0.5, 'temperature': 0.8, 'user_engine': 'user'}, 'algorithm': {'gamma': 1.0, 'lam': 1.0, 'adv_estimator': 'grpo', 'no_think_rl': False, 'kl_penalty': 'kl', 'kl_ctrl': {'type': 'fixed', 'kl_coef': 0.001}, 'state_masking': {'start_state_marker': '<information>', 'end_state_marker': '</information>'}}, 'trainer': {'total_epochs': 10, 'total_training_steps': 203, 'project_name': 'ZeroSearch', 'experiment_name': 'Qwen2.5-0.5B-Instruct_GRPO_wiki_models/iic/Simulation_LLM_google_3B_0_0.5_wiki_turns_5', 'logger': ['wandb'], 'nnodes': 1, 'n_gpus_per_node': 2, 'save_freq': 50, 'test_freq': 300, 'critic_warmup': 0, 'default_hdfs_dir': None, 'default_local_dir': 'verl_checkpoints/Qwen2.5-0.5B-Instruct_GRPO_wiki_models/iic/Simulation_LLM_google_3B_0_0.5_wiki_turns_5', 'do_search': True, 'do_user': True, 'max_turns': 5, 'val_before_train': False, 'val_only': False, 'reward_function': 'f1'}, '_wandb': {}}
2025-10-16 11:34:03,981 INFO    MainThread:1853794 [wandb_init.py:init():880] starting backend
2025-10-16 11:34:04,285 INFO    MainThread:1853794 [wandb_init.py:init():883] sending inform_init request
2025-10-16 11:34:04,289 INFO    MainThread:1853794 [wandb_init.py:init():891] backend started and connected
2025-10-16 11:34:04,295 INFO    MainThread:1853794 [wandb_init.py:init():961] updated telemetry
2025-10-16 11:34:04,296 INFO    MainThread:1853794 [wandb_init.py:init():985] communicating run to backend with 90.0 second timeout
2025-10-16 11:34:05,040 INFO    MainThread:1853794 [wandb_init.py:init():1036] starting run threads in backend
2025-10-16 11:34:05,178 INFO    MainThread:1853794 [wandb_run.py:_console_start():2509] atexit reg
2025-10-16 11:34:05,178 INFO    MainThread:1853794 [wandb_run.py:_redirect():2357] redirect: wrap_raw
2025-10-16 11:34:05,178 INFO    MainThread:1853794 [wandb_run.py:_redirect():2426] Wrapping output streams.
2025-10-16 11:34:05,178 INFO    MainThread:1853794 [wandb_run.py:_redirect():2449] Redirects installed.
2025-10-16 11:34:05,182 INFO    MainThread:1853794 [wandb_init.py:init():1076] run started, returning control to user process
2025-10-16 11:35:08,405 INFO    wandb-AsyncioManager-main:1853794 [service_client.py:_forward_responses():80] Reached EOF.
2025-10-16 11:35:08,405 INFO    wandb-AsyncioManager-main:1853794 [mailbox.py:close():137] Closing mailbox, abandoning 1 handles.
2025-10-16 11:35:09,913 ERROR   MainThread:1853794 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2430, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1595, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 802, in publish_output_raw
    self._publish_output_raw(o)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 37, in _publish_output_raw
    self._publish(rec)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 43, in _publish
    self._asyncer.run(lambda: self._client.publish(request))
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/lib/asyncio_manager.py", line 136, in run
    return future.result()
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/lib/asyncio_manager.py", line 219, in _wrap
    return await fn()
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/lib/service/service_client.py", line 38, in publish
    await self._send_server_request(request)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/lib/service/service_client.py", line 64, in _send_server_request
    await self._writer.drain()
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
2025-10-16 11:35:10,428 ERROR   ray_print_logs:1853794 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2430, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1595, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 802, in publish_output_raw
    self._publish_output_raw(o)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 37, in _publish_output_raw
    self._publish(rec)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 43, in _publish
    self._asyncer.run(lambda: self._client.publish(request))
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/lib/asyncio_manager.py", line 136, in run
    return future.result()
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/lib/asyncio_manager.py", line 219, in _wrap
    return await fn()
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/lib/service/service_client.py", line 38, in publish
    await self._send_server_request(request)
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/site-packages/wandb/sdk/lib/service/service_client.py", line 64, in _send_server_request
    await self._writer.drain()
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/ssd/chenxi/miniconda3/envs/criticsearch/lib/python3.9/asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
